/**
 * モンスターのドット絵（後半・ボス含む）。
 *
 * すべて 16x16。キーは monsters.ts の id。
 * 同じ family は tier をまたいでシルエットを共有し、色と装飾で差をつける。
 */

import type { PixelSprite } from '../sprites.js';

export const MONSTER_SPRITES_B: Record<string, PixelSprite> = {
  // ===================================================== おばけ系（半透明の白青・下は尾を引く）
  ghostPale: {
    palette: { o: '#2d2a55', b: '#cfe0f7', s: '#8fa4cf', w: '#ffffff', e: '#332f5e' },
    rows: [
      '................',
      '.....oooooo.....',
      '....obbbbbbo....',
      '...obwbbbbbbo...',
      '...obeebbeebo...',
      '...obeebbeebo...',
      '...obbbbbbbbo...',
      '...obbbeebbbo...',
      '...obbbbbbbso...',
      '...obbbbbbbso...',
      '...obbbbbbbso...',
      '...obbbbbbbso...',
      '...obbbbbbbso...',
      '...obbobbobbo...',
      '....oo.oo.oo....',
      '................',
    ],
    shadow: true,
  },

  ghostGrudge: {
    palette: { o: '#2a1038', b: '#bb96dd', s: '#7d57a6', w: '#e6d2f7', e: '#ffd94a' },
    rows: [
      '................',
      '.....oooooo.....',
      '....obbbbbbo....',
      '...oboobboobo...',
      '...obeebbeebo...',
      '...obeebbeebo...',
      '...obbbbbbbbo...',
      '...oboeeeeobo...',
      '...obwbbbbbso...',
      '...obbbbbbbso...',
      '...obbbbbbbso...',
      '...obbbbbbbso...',
      '...obbbbbbbso...',
      '...obbobbobbo...',
      '....oo.oo.oo....',
      '................',
    ],
    shadow: true,
  },

  ghostReaper: {
    palette: { o: '#150e2c', b: '#7884b4', s: '#454e7c', w: '#b3bce0', e: '#ff4646' },
    rows: [
      '................',
      '....o.oooo.o....',
      '....obbbbbbo....',
      '...oboobboobo...',
      '...obeebbeebo...',
      '...obeebbeebo...',
      '...obbbbbbbbo...',
      '...oeoeeeeoeo...',
      '...obwbbbbbso...',
      '...obbbbbbbso...',
      '...obbbbbbbso...',
      '...obbbbbbbso...',
      '...obbbbbbbso...',
      '...obbobbobbo...',
      '....oo.oo.oo....',
      '................',
    ],
    shadow: true,
  },

  // ===================================================== すいとり系（吸い付く口・紫）
  drainLesser: {
    palette: { o: '#2a0f3a', b: '#9d55c4', s: '#68308c', m: '#f5a2d6', e: '#ffe96f' },
    rows: [
      '................',
      '.....oooooo.....',
      '...oobbbbbboo...',
      '..obbbbbbbbbbo..',
      '..obbeebbeebbo..',
      '..obbeebbeebbo..',
      '..obbbbbbbbbbo..',
      '..obbbommobbbo..',
      '..obbommmmobbo..',
      '..obbommmmobbo..',
      '..obbbommobbso..',
      '..obbbbbbbbbso..',
      '...obbbbbbbso...',
      '....obbbbbbo....',
      '.....oooooo.....',
      '................',
    ],
    shadow: true,
  },

  drainGreater: {
    palette: { o: '#1a0630', b: '#7a3fd0', s: '#3f1d80', m: '#ff6fb4', e: '#fff2a0' },
    rows: [
      '................',
      '...o.oooooo.o...',
      '...oobbbbbboo...',
      '..obbbbbbbbbbo..',
      '..obbeebbeebbo..',
      '..obbeebbeebbo..',
      '..obbobbbbobbo..',
      '..obbommmmobbo..',
      '..obommmmmmobo..',
      '..obommmmmmobo..',
      '..obbommmmobso..',
      '..obbbbbbbbbso..',
      '...obbbbbbbso...',
      '....obbbbbbo....',
      '.....oooooo.....',
      '................',
    ],
    shadow: true,
  },

  // ===================================================== サビ系（錆色の虫 → 竜）
  rustBug: {
    palette: { o: '#2a1409', b: '#a8643a', s: '#6e3d1f', w: '#d69a63', e: '#ffd27a' },
    rows: [
      '................',
      '...o........o...',
      '....o......o....',
      '.....oooooo.....',
      '....obbbbbbo....',
      '....obebbebo....',
      '....obboobbo....',
      '..obbbbbbbbbbo..',
      '.oobbwwwwbbbsoo.',
      '..obbwwwwbbbso..',
      '..obbbbbbbbbso..',
      '.oobbbbbbbbbsoo.',
      '..obbbbbbbbbso..',
      '...obbbbbbbso...',
      '....oooooooo....',
      '................',
    ],
    shadow: true,
  },

  rustWyrm: {
    palette: { o: '#2a1409', b: '#b8703c', s: '#7a4220', w: '#e0a86a', e: '#8ef0c0' },
    rows: [
      '................',
      '..o..........o..',
      '..oo..oooo..oo..',
      '.ossoobbbboosso.',
      '.ossobebbebosso.',
      '.osoobboobbooso.',
      '.oo.obwbbwbo.oo.',
      '.....obbbbo.....',
      '....obbbbbbo....',
      '...obbwwwwbbo...',
      '...obbwwwwbbo...',
      '...obbbbbbbso...',
      '..obbbbbbbbbso..',
      '..obbbbbbbbbso..',
      '...oooooooooo...',
      '................',
    ],
    shadow: true,
  },

  // ===================================================== のろい面系（ひび割れた面）
  cursedMask: {
    palette: { o: '#2b1420', b: '#e8dcc0', s: '#ac9470', e: '#3a1418', r: '#b02a2a' },
    rows: [
      '................',
      '...oooooooooo...',
      '..obbbbbbbbbbo..',
      '..obbbbbbbbbbo..',
      '..obbbbbbbbbbo..',
      '..oboeebbeeobo..',
      '..oboeebbeeobo..',
      '..obbbbrrbbbso..',
      '..obbbrbbbbbso..',
      '..obboeeeeobso..',
      '..obborrrrobso..',
      '..obbboooobbso..',
      '..obbbbbbbbbso..',
      '...obbbbbbbso...',
      '....oooooooo....',
      '................',
    ],
    shadow: true,
  },

  cursedMaskGreat: {
    palette: { o: '#1c0a26', b: '#d8b84e', s: '#93731d', e: '#2a0a30', r: '#8a3ce0' },
    rows: [
      '................',
      '...oooooooooo...',
      '..obbbbbbbbbbo..',
      '..obbrrbbrrbbo..',
      '..obbbbbbbbbbo..',
      '..oboeebbeeobo..',
      '..oboeebbeeobo..',
      '..obbbbrrbbbso..',
      '..obbbrbbbbbso..',
      '..obboeeeeobso..',
      '..obborrrrobso..',
      '..obbboooobbso..',
      '..obbbbbbbbbso..',
      '...obbbbbbbso...',
      '....oooooooo....',
      '................',
    ],
    shadow: true,
  },

  // ===================================================== ばけもの系（壺／巻物に牙と目）
  mimicPot: {
    palette: { o: '#2a1a2e', b: '#5f9ab0', s: '#3a6a80', w: '#9ed4e4', e: '#ffe24a', f: '#ffffff' },
    rows: [
      '................',
      '....oooooooo....',
      '...obbbbbbbbo...',
      '..obbbbbbbbbbo..',
      '.obbbbbbbbbbbbo.',
      '.obbeebbbbeebbo.',
      '.obbeebbbbeebso.',
      '.obbbbbbbbbbbso.',
      '.obofofofofobso.',
      '.obooooooooobso.',
      '.obbbbbbbbbbbso.',
      '.obwbbbbbbbbbso.',
      '.obbbbbbbbbbbso.',
      '..obbbbbbbbbso..',
      '...oooooooooo...',
      '................',
    ],
    shadow: true,
  },

  mimicScroll: {
    palette: { o: '#2a2118', b: '#e8dcb4', s: '#b09a6a', e: '#ff4a4a', f: '#ffffff', r: '#8a3020' },
    rows: [
      '................',
      '................',
      '..oooooooooooo..',
      '.orbbbbbbbbbbro.',
      '.orbbbbbbbbbbro.',
      '.orbeebbbbeebro.',
      '.orbeebbbbeebro.',
      '.orbbbbbbbbbbro.',
      '.orbofofofobsro.',
      '.orbooooooobsro.',
      '.orbbbbbbbbbsro.',
      '.orbbbbbbbbbsro.',
      '.orbbbbbbbbbsro.',
      '..oooooooooooo..',
      '................',
      '................',
    ],
    shadow: true,
  },

  // ===================================================== かげ系（黒い人影・目だけ光る）
  shadowClone: {
    palette: { o: '#0e0b18', b: '#4a4370', s: '#2a2444', w: '#6f66a0', e: '#7fe8ff' },
    rows: [
      '................',
      '.....oooooo.....',
      '....obwbbbbo....',
      '....obbbbbbo....',
      '....oeebbeeo....',
      '....obbbbbbo....',
      '..oobbbbbbbboo..',
      '.oowbbbbbbbbsoo.',
      '.oobbbbbbbbbsoo.',
      '..obbbbbbbbbso..',
      '..obbbbbbbbbso..',
      '...obbbbbbbso...',
      '...obbo..obbo...',
      '...obbo..obbo...',
      '...oooo..oooo...',
      '................',
    ],
    shadow: true,
  },

  shadowLord: {
    palette: { o: '#0a0714', b: '#5b3f8c', s: '#301d56', w: '#8a6bc4', e: '#ff6be0' },
    rows: [
      '................',
      '....o.oooo.o....',
      '....obwbbbbo....',
      '....obbbbbbo....',
      '....oeebbeeo....',
      '....obbbbbbo....',
      '..oobbbbbbbboo..',
      '.oowbbbbbbbbsoo.',
      '.oobbbbbbbbbsoo.',
      '..obbbbbbbbbso..',
      '..obbbbbbbbbso..',
      '...obbbbbbbso...',
      '...obbo..obbo...',
      '...obbo..obbo...',
      '...oooo..oooo...',
      '................',
    ],
    shadow: true,
  },

  // ===================================================== ころばし系（棒に目と手）
  tripStick: {
    palette: { o: '#2a1c10', b: '#c09a52', s: '#8a6a2e', e: '#ffffff', p: '#e8d27a' },
    rows: [
      '................',
      '.....oooooo.....',
      '....obbbbbbo....',
      '....oeobboeo....',
      '....oeebbeeo....',
      '....obbbbbbo....',
      '.....obbbbo.....',
      '.obo.obbbbo.obo.',
      '.obbbbbbbbbbbbo.',
      '.ooooobbbsooooo.',
      '.....opbbso.....',
      '.....opbbso.....',
      '.....obbbso.....',
      '.....obbbso.....',
      '.....oooooo.....',
      '................',
    ],
    shadow: true,
  },

  tripPole: {
    palette: { o: '#25100a', b: '#d0603a', s: '#8e3418', e: '#fff0c0', p: '#f0a070' },
    rows: [
      '................',
      '.....oooooo.....',
      '....obbbbbbo....',
      '....oeobboeo....',
      '....oeebbeeo....',
      '....obbbbbbo....',
      '.....obbbbo.....',
      '.obo.obbbbo.obo.',
      '.obbbbbbbbbbbbo.',
      '.ooooobbbsooooo.',
      '.....opbbso.....',
      '.....opppso.....',
      '.....obbbso.....',
      '.....opppso.....',
      '.....oooooo.....',
      '................',
    ],
    shadow: true,
  },

  // ===================================================== 武者系（甲冑・兜の前立て）
  armorWood: {
    palette: { o: '#2a1a0e', b: '#a5763f', s: '#6d4a22', w: '#d0a468', c: '#8d8a5e', e: '#ffd84a' },
    rows: [
      '................',
      '.......oo.......',
      '......occo......',
      '...ooooccoooo...',
      '..obbbbccbbbbo..',
      '..obbbbbbbbbbo..',
      '...oboeooeobo...',
      '...oboooooobo...',
      '.oobbbbbbbbbsoo.',
      '.obbobbbbbbosso.',
      '.obbobbbbbbosso.',
      '...obbwwwwbbo...',
      '...obbwwwwbbo...',
      '...obbo..obbo...',
      '...oooo..oooo...',
      '................',
    ],
    shadow: true,
  },

  armorIron: {
    palette: { o: '#1c2028', b: '#b4bcc8', s: '#6e7886', w: '#e4ecf4', c: '#c8a040', e: '#ff5a3a' },
    rows: [
      '................',
      '......o..o......',
      '......occo......',
      '...ooooccoooo...',
      '..obbbbccbbbbo..',
      '..obbbbbbbbbbo..',
      '...oboeooeobo...',
      '...oboooooobo...',
      '.oobbbbbbbbbsoo.',
      '.obbobbbbbbosso.',
      '.obbobbbbbbosso.',
      '...obbwwwwbbo...',
      '...obbwwwwbbo...',
      '...obbo..obbo...',
      '...oooo..oooo...',
      '................',
    ],
    shadow: true,
  },

  armorBlack: {
    palette: { o: '#100f18', b: '#4c4a62', s: '#2b2a3c', w: '#767494', c: '#c0342c', e: '#ff3a3a' },
    rows: [
      '................',
      '.....oc..co.....',
      '......occo......',
      '...ooooccoooo...',
      '..obbbbccbbbbo..',
      '..obbbbbbbbbbo..',
      '...oboeooeobo...',
      '...oboooooobo...',
      '.oobbbbbbbbbsoo.',
      '.obbobbbbbbosso.',
      '.obbobbbbbbosso.',
      '...obbwwwwbbo...',
      '...obbwwwwbbo...',
      '...obbo..obbo...',
      '...oooo..oooo...',
      '................',
    ],
    shadow: true,
  },

  armorTenrin: {
    palette: { o: '#3a2608', b: '#e8c24e', s: '#a07818', w: '#fff0b0', c: '#eaf4ff', e: '#4ad8ff' },
    rows: [
      '................',
      '.....occcco.....',
      '......occo......',
      '...ooooccoooo...',
      '..obbbbccbbbbo..',
      '..obbbbbbbbbbo..',
      '...oboeooeobo...',
      '...oboooooobo...',
      '.oobbbbbbbbbsoo.',
      '.obbobbbbbbosso.',
      '.obbobbbbbbosso.',
      '...obbwwwwbbo...',
      '...obbwwwwbbo...',
      '...obbo..obbo...',
      '...oooo..oooo...',
      '................',
    ],
    shadow: true,
  },

  // ===================================================== おに系（角と金棒）
  ogreRed: {
    palette: {
      o: '#3a0f10', b: '#d9503c', s: '#8f2a20', w: '#f58a72',
      h: '#f2e4c0', k: '#7a5a2e', e: '#ffe24a',
    },
    rows: [
      '................',
      '....o......o....',
      '....h......h....',
      '...ohooooooho...',
      '...obbbbbbbbo...',
      '...obeobboebo...',
      '...obbboobbbo...',
      '...obohoohobo...',
      '.oobbbbbbbbsoko.',
      '.obbobwbbbsooko.',
      '.obbobbbbbbsoko.',
      '...obbbbbbbso...',
      '...obbbbbbbso...',
      '...obbo..obbo...',
      '...oooo..oooo...',
      '................',
    ],
    shadow: true,
  },

  ogreBlue: {
    palette: {
      o: '#0c1c3a', b: '#4a7ad8', s: '#23407e', w: '#8ab4f5',
      h: '#f2e4c0', k: '#8a8a9a', e: '#ffe24a',
    },
    rows: [
      '................',
      '....o......o....',
      '....h......h....',
      '...ohooooooho...',
      '...obbbbbbbbo...',
      '...obeobboebo...',
      '...obbboobbbo...',
      '...obohoohobo...',
      '.oobbbbbbbbsoko.',
      '.obbobwbbbsooko.',
      '.obbobbbbbbsoko.',
      '...obbbbbbbso...',
      '...obbbbbbbso...',
      '...obbo..obbo...',
      '...oooo..oooo...',
      '................',
    ],
    shadow: true,
  },

  ogreKing: {
    palette: {
      o: '#2a0810', b: '#c03a6a', s: '#7a1c40', w: '#f08aa8',
      h: '#fff0c0', k: '#e8c24e', e: '#fff0f0',
    },
    rows: [
      '................',
      '....h......h....',
      '....h......h....',
      '...ohooooooho...',
      '...obbbbbbbbo...',
      '...obeobboebo...',
      '...obbboobbbo...',
      '...obohoohobo...',
      '.oobbbbbbbbsoko.',
      '.obbobwbbbsooko.',
      '.obbobbbbbbsoko.',
      '...obbbbbbbso...',
      '...obbbbbbbso...',
      '...obbo..obbo...',
      '...oooo..oooo...',
      '................',
    ],
    shadow: true,
  },

  // ===================================================== 竜系（トカゲ → 翼と炎の竜）
  lizardFire: {
    palette: { o: '#2a1206', b: '#d86a2a', s: '#933f10', w: '#f5a856', f: '#ffe14a', e: '#fff0c0' },
    rows: [
      '................',
      '................',
      '.....oooooo.....',
      '....obbbbbbo....',
      '....obebbebo....',
      '....obbbbbbo....',
      '....oboffobo....',
      '..oobbbbbbbboo..',
      '.oobbbwwbbbbsoo.',
      '..obbbwwbbbbso..',
      '..obbbbbbbbbsoo.',
      '..obbbbbbbbbsbo.',
      '..obbo..obbosbo.',
      '..oooo..ooooooo.',
      '................',
      '................',
    ],
    shadow: true,
  },

  dragonFlame: {
    palette: { o: '#2a0a06', b: '#e0502a', s: '#96240f', w: '#ffa24a', f: '#ffe14a', e: '#fff4c0' },
    rows: [
      '................',
      '.oo..........oo.',
      '.oso.oooooo.oso.',
      '.ossobbbbbbosso.',
      '.ossobebbebosso.',
      '.oosoboffobosoo.',
      '..oo.obbbbo.oo..',
      '....obbbbbbo....',
      '...obbwwwwbbo...',
      '..obbwwffwwbbo..',
      '..obbwwffwwbso..',
      '..obbbbbbbbbso..',
      '..obbbbbbbbbso..',
      '..obbo..obbosoo.',
      '..oooo..oooooo..',
      '................',
    ],
    shadow: true,
  },

  dragonInferno: {
    palette: { o: '#2e0604', b: '#ff6a2a', s: '#a81c08', w: '#ffc24a', f: '#fff6b0', e: '#7fe8ff' },
    rows: [
      '................',
      '.oo..........oo.',
      '.oso.oooooo.oso.',
      '.ossobbbbbbosso.',
      '.ossobebbebosso.',
      '.oosooffffoosoo.',
      '..oo.obbbbo.oo..',
      '....obbbbbbo....',
      '...obbwwwwbbo...',
      '..obwwffffwwbo..',
      '..obwwffffwwso..',
      '..obbbbbbbbbso..',
      '..obbbbbbbbbso..',
      '..obbo..obbosoo.',
      '..oooo..oooooo..',
      '................',
    ],
    shadow: true,
  },

  // ===================================================== 水棲系（魚 → 大うなぎ → 水竜）
  fishSmall: {
    palette: { o: '#0c1c36', b: '#4fa8d8', s: '#26638f', w: '#a8e0f5', e: '#ffffff' },
    rows: [
      '................',
      '................',
      '.....oooooo.....',
      '....obbbbbbo....',
      '...obbbbbbbbo...',
      '...obeobboebo...',
      '...obbbbbbbbo...',
      '...obboooobbo...',
      '...obbbwwbbbo...',
      '...obbbbbbbso...',
      '....obbbbbbo....',
      '..oo.obbbbo.oo..',
      '.obbo.oooo.obbo.',
      '.oooo......oooo.',
      '................',
      '................',
    ],
    shadow: true,
  },

  eelGiant: {
    palette: { o: '#0a1a2e', b: '#3f8fae', s: '#1e5570', w: '#8fd4e8', e: '#ffe24a', m: '#e06a8a' },
    rows: [
      '................',
      '....oooooooo....',
      '..oobbbbbbbboo..',
      '.obwbbbbbbbbbbo.',
      '.obbeebbbbeebbo.',
      '.obbeebbbbeebso.',
      '.obbbbbbbbbbbso.',
      '.obooooooooobso.',
      '.obommmmmmmobso.',
      '.obommmmmmmobso.',
      '.obooooooooobso.',
      '..obbbbbbbbbso..',
      '...obbbbbbbso...',
      '....obbbbbso....',
      '....oooooooo....',
      '................',
    ],
    shadow: true,
  },

  waterDragon: {
    palette: { o: '#08182e', b: '#2f7fd8', s: '#164a8e', w: '#8fd0ff', e: '#ffe24a', f: '#b8f0ff' },
    rows: [
      '................',
      '.oo..........oo.',
      '.ofo.oooooo.ofo.',
      '.offobbbbbboffo.',
      '.offobebbeboffo.',
      '.oofoboffobofoo.',
      '..oo.obbbbo.oo..',
      '....obbbbbbo....',
      '...obbwwwwbbo...',
      '..obbwwffwwbbo..',
      '..obbwwffwwbso..',
      '..obbbbbbbbbso..',
      '..obbbbbbbbbso..',
      '..obbo..obbosoo.',
      '..oooo..oooooo..',
      '................',
    ],
    shadow: true,
  },

  // ===================================================== カエル系（大きな口）
  frogTree: {
    palette: { o: '#12280c', b: '#6fc04a', s: '#3a7a22', w: '#b0e878', e: '#ffe24a', m: '#e05a7a' },
    rows: [
      '................',
      '...oo......oo...',
      '..oeeo....oeeo..',
      '..oeoo.oo.ooeo..',
      '.oobbbbbbbbbboo.',
      '.obbbbbbbbbbbso.',
      '.obwbbbbbbbbbso.',
      '.obooooooooobso.',
      '.obommmmmmmobso.',
      '.obooooooooobso.',
      '.obbbbbbbbbbbso.',
      '.obbbbbbbbbbbso.',
      '..obbbbbbbbbso..',
      '.obbo.oooo.obbo.',
      '.oooo......oooo.',
      '................',
    ],
    shadow: true,
  },

  frogGiant: {
    palette: { o: '#101a0a', b: '#8aa832', s: '#4e6414', w: '#c8dc72', e: '#ff6a4a', m: '#c04a6a' },
    rows: [
      '................',
      '...oo......oo...',
      '..oeeo....oeeo..',
      '..oeoo.oo.ooeo..',
      '.oobbbbbbbbbboo.',
      '.obbbbbbbbbbbso.',
      '.obwbbbbbbbbbso.',
      '.obooooooooobso.',
      '.obommmmmmmobso.',
      '.obommmmmmmobso.',
      '.obooooooooobso.',
      '.obbbbbbbbbbbso.',
      '..obbbbbbbbbso..',
      '.obbo.oooo.obbo.',
      '.oooo......oooo.',
      '................',
    ],
    shadow: true,
  },

  // ===================================================== はがね系（金属光沢の虫）
  metalBug: {
    palette: { o: '#151a22', b: '#9aa8bc', s: '#5a6678', w: '#ffffff', h: '#e0e8f4', e: '#ffd24a' },
    rows: [
      '................',
      '...o........o...',
      '....o......o....',
      '.....oooooo.....',
      '....obbbbbbo....',
      '....obebbebo....',
      '....obboobbo....',
      '..obbbbbbbbbbo..',
      '.oobwwwhhbbbsoo.',
      '..obwwwhhbbbso..',
      '..obbwhhbbbbso..',
      '.oobbbbbbbbbsoo.',
      '..obbbbbbbbbso..',
      '...obbbbbbbso...',
      '....oooooooo....',
      '................',
    ],
    shadow: true,
  },

  metalKing: {
    palette: { o: '#141018', b: '#d8dce8', s: '#7e8698', w: '#ffffff', h: '#f4f8ff', c: '#ffd24a' },
    rows: [
      '................',
      '....c.cccc.c....',
      '....oooooooo....',
      '....obbbbbbo....',
      '....obcbbcbo....',
      '....obboobbo....',
      '..obbbbbbbbbbo..',
      '.oobwwwhhbbbsoo.',
      '..obwwwhhbbbso..',
      '..obbwhhbbbbso..',
      '.oobbbbbbbbbsoo.',
      '..obbbbbbbbbso..',
      '..obbbbbbbbbso..',
      '...obbbbbbbso...',
      '....oooooooo....',
      '................',
    ],
    shadow: true,
  },

  // ===================================================== ボム系（導火線のついた球体）
  bombSlime: {
    palette: { o: '#1c1228', b: '#7a6ad0', s: '#443a86', w: '#b0a4f0', f: '#ff9a2a', e: '#ffe24a' },
    rows: [
      '................',
      '.........ff.....',
      '........fo......',
      '.......oo.......',
      '...oooooooooo...',
      '..obbbbbbbbbbo..',
      '.obbbbbbbbbbbbo.',
      '.obbeebbbbeebbo.',
      '.obbeebbbbeebso.',
      '.obwbbboobbbbso.',
      '.obbbbboobbbbso.',
      '.obbbbbbbbbbbso.',
      '..obbbbbbbbbso..',
      '...obbbbbbbso...',
      '....oooooooo....',
      '................',
    ],
    shadow: true,
  },

  bombGiant: {
    palette: { o: '#2a0c10', b: '#d84a3a', s: '#8a1c18', w: '#ffa080', f: '#ffe24a', e: '#fff0b0' },
    rows: [
      '................',
      '........ffff....',
      '........fo......',
      '.......oo.......',
      '...oooooooooo...',
      '..obbbbbbbbbbo..',
      '.obbbbbbbbbbbbo.',
      '.obbeebbbbeebbo.',
      '.obbeebbbbeebso.',
      '.obwbbboobbbbso.',
      '.obbbbboobbbbso.',
      '.obbbbbbbbbbbso.',
      '..obbbbbbbbbso..',
      '...obbbbbbbso...',
      '....oooooooo....',
      '................',
    ],
    shadow: true,
  },

  // ===================================================== 目系（大きな一つ目）
  eyeGaze: {
    palette: { o: '#20102a', b: '#d8c8e8', s: '#8f7aa8', i: '#4fc0e0', p: '#1a0c20', w: '#ffffff' },
    rows: [
      '................',
      '................',
      '....oooooooo....',
      '..oobbbbbbbboo..',
      '.obbbbbbbbbbbbo.',
      '.obbboooooobbbo.',
      '.obboiiiiiiobso.',
      '.oboiiippiiioso.',
      '.oboiiwppiiioso.',
      '.obboiiiiiiobso.',
      '.obbboooooobbso.',
      '.obbbbbbbbbbbso.',
      '..obbbbbbbbbso..',
      '...oooooooooo...',
      '................',
      '................',
    ],
    shadow: true,
  },

  eyeAbyss: {
    palette: { o: '#12061c', b: '#6a4a8e', s: '#3a2352', i: '#ff3a5a', p: '#0a0310', w: '#ffd0e0' },
    rows: [
      '................',
      '...o........o...',
      '....oooooooo....',
      '..oobbbbbbbboo..',
      '.obbbbbbbbbbbbo.',
      '.obbboooooobbbo.',
      '.obboiiiiiiobso.',
      '.oboiiippiiioso.',
      '.oboiiwppiiioso.',
      '.obboiiiiiiobso.',
      '.obbboooooobbso.',
      '.obbbbbbbbbbbso.',
      '..obbbbbbbbbso..',
      '...oooooooooo...',
      '................',
      '................',
    ],
    shadow: true,
  },

  // ===================================================== おどり系（浮いた壺／道具）
  polterPot: {
    palette: { o: '#20141c', b: '#b06a3a', s: '#70401e', w: '#e0a066', g: '#8ff0e0', e: '#ffe24a' },
    rows: [
      '................',
      '....oooooooo....',
      '...obbbbbbbbo...',
      '..obbbbbbbbbbo..',
      '.obbbbbbbbbbbbo.',
      '.obbeebbbbeebbo.',
      '.obbeebbbbeebso.',
      '.obwbbbbbbbbbso.',
      '.obbbbwwwwbbbso.',
      '.obbbbwwwwbbbso.',
      '.obbbbbbbbbbbso.',
      '..obbbbbbbbbso..',
      '...oooooooooo...',
      '....g.g..g.g....',
      '.....gg..gg.....',
      '................',
    ],
    shadow: false,
  },

  polterLord: {
    palette: { o: '#1a0e24', b: '#7a4a9e', s: '#46246a', w: '#e8c24e', g: '#ff8fe0', e: '#fff0a0' },
    rows: [
      '................',
      '....o.oooo.o....',
      '...obbbbbbbbo...',
      '..obbbbbbbbbbo..',
      '.obbbbbbbbbbbbo.',
      '.obbeebbbbeebbo.',
      '.obbeebbbbeebso.',
      '.obwbbbbbbbbbso.',
      '.obbbbwwwwbbbso.',
      '.obbbbwwwwbbbso.',
      '.obbbbbbbbbbbso.',
      '..obbbbbbbbbso..',
      '...oooooooooo...',
      '....g.g..g.g....',
      '.....gg..gg.....',
      '................',
    ],
    shadow: false,
  },

  // ===================================================== ふち系（深層の強敵・暗紫に光る目）
  abyssWatcher: {
    palette: { o: '#0d0616', b: '#4a2a6e', s: '#2a1442', e: '#7fffd0', w: '#6f4499', r: '#c85ae8' },
    rows: [
      '................',
      '.....oooooo.....',
      '....obbbbbbo....',
      '...obbbbbbbbo...',
      '...obeobboebo...',
      '...obbbbbbbbo...',
      '..oobbbbbbbboo..',
      '.obbbbbrrbbbbbo.',
      '.obbbbrrrrbbbso.',
      '.obwbbbrrbbbbso.',
      '.obbbbbbbbbbbso.',
      '..obbbbbbbbbso..',
      '..obbbbbbbbbso..',
      '..obbobbbbobbo..',
      '..oooooooooooo..',
      '................',
    ],
    shadow: true,
  },

  abyssDevourer: {
    palette: { o: '#0a0410', b: '#5e2a6e', s: '#340f42', e: '#ffde4a', w: '#8a3f9e', r: '#ff4a7a' },
    rows: [
      '................',
      '.....oooooo.....',
      '....obbbbbbo....',
      '...obbbbbbbbo...',
      '...obeobboebo...',
      '...obbbbbbbbo...',
      '..oobbbbbbbboo..',
      '.obooooooooobso.',
      '.oborrrrrrrobso.',
      '.obooooooooobso.',
      '.obwbbbbbbbbbso.',
      '..obbbbbbbbbso..',
      '..obbbbbbbbbso..',
      '..obbobbbbobbo..',
      '..oooooooooooo..',
      '................',
    ],
    shadow: true,
  },

  abyssSovereign: {
    palette: { o: '#0a0212', b: '#7a3ac0', s: '#42147e', e: '#ffffff', w: '#a86ae0', r: '#ffd24a' },
    rows: [
      '................',
      '...o.oooooo.o...',
      '...obbbbbbbbo...',
      '...obbbbbbbbo...',
      '...obeobboebo...',
      '...obbbbbbbbo...',
      '..oobbbbbbbboo..',
      '.obbbbbrrbbbbbo.',
      '.obbbrrrrrrbbso.',
      '.obwbbrrrrbbbso.',
      '.obbbbbrrbbbbso.',
      '..obbbbbbbbbso..',
      '..obbbbbbbbbso..',
      '..obbobbbbobbo..',
      '..oooooooooooo..',
      '................',
    ],
    shadow: true,
  },

  // ===================================================== 店主・番犬
  shopkeeper: {
    palette: { o: '#241810', b: '#f0c898', s: '#b08a5a', a: '#3a7ac0', g: '#e8c24e', h: '#4a2e18' },
    rows: [
      '................',
      '.....oooooo.....',
      '....ohhhhhho....',
      '...ohhhhhhhho...',
      '...obbbbbbbbo...',
      '...obobbbbobo...',
      '...obbboobbbo...',
      '..oobbbbbbbboo..',
      '.obbaaaaaaaabbo.',
      '.obbaaaaaaaabso.',
      '.obbaagggaaabso.',
      '.obaaagggaaabso.',
      '..oaaaaoaaaaso..',
      '..oaaao.oaaaso..',
      '..ooooo..ooooo..',
      '................',
    ],
    shadow: true,
  },

  shopGuard: {
    palette: { o: '#1e1208', b: '#c08a44', s: '#7e5220', w: '#e8bc78', e: '#ff4a3a', t: '#f0f0e0' },
    rows: [
      '................',
      '...oo......oo...',
      '..obbo....obbo..',
      '..obbboooobbbo..',
      '..obbbbbbbbbbo..',
      '..obebbbbbbebo..',
      '..obbbboobbbbo..',
      '..obbbottobbbo..',
      '..obbbooooobbo..',
      '.oobbbbbbbbbboo.',
      '.obbwwbbbbbbbso.',
      '.obbwwbbbbbbbso.',
      '..obbbbbbbbbso..',
      '..obbo..obbosoo.',
      '..oooo..ooooooo.',
      '................',
    ],
    shadow: true,
  },

  // ===================================================== ボス（他より大きく・豪華に）
  bossForest: {
    palette: {
      o: '#1c1206', b: '#c8a052', s: '#7e5a20', w: '#f0d8a0',
      e: '#5ae8a0', m: '#3a2a12', t: '#ffffff',
    },
    rows: [
      '................',
      '.obo.oooooo.obo.',
      '.obbobbbbbbobbo.',
      '.obbbbbbbbbbbbo.',
      '.obmbbbbbbbbmbo.',
      '.oboeebbbbeeobo.',
      '.obooebbbbeoobo.',
      '.obbbbbmmbbbbbo.',
      '.obbbottttobbbo.',
      '.obbbommmmobbbo.',
      '.obbbbbbbbbbbbo.',
      '.obwwbbbbbbbbso.',
      '.obwwbbbbbbbbso.',
      '.obbobbbbbbobbo.',
      '.oooo.oooo.oooo.',
      '................',
    ],
    shadow: true,
  },

  bossVolcano: {
    palette: {
      o: '#2a1408', b: '#a86a48', s: '#68381e', w: '#d8a072',
      f: '#ff8a2a', h: '#f0e0b0', e: '#ffe24a',
    },
    rows: [
      '................',
      '..h..........h..',
      '..hhoooooooohh..',
      '.ohhbbbbbbbbhho.',
      '.obbbbbbbbbbbbo.',
      '.obbeeobboeebbo.',
      '.obbeeobboeebso.',
      '.obbbbbffbbbbso.',
      '.obohhhhhhhobso.',
      '.obbbbbbbbbbbso.',
      '.obbbffffbbbbso.',
      '.obbbffffbbbbso.',
      '.obbbbwwwwbbbso.',
      '.obbbo.oo.obbso.',
      '.ooooo.oo.ooooo.',
      '................',
    ],
    shadow: true,
  },

  bossWaterway: {
    palette: {
      o: '#04101c', b: '#2a6a8e', s: '#123a52', w: '#6fb8d0',
      e: '#a8ff5a', m: '#0a2030', t: '#e8f8ff',
    },
    rows: [
      '................',
      '.ob.ob....bo.bo.',
      '..oboboooobobo..',
      '.obbbbbbbbbbbbo.',
      '.obbbbbbbbbbbbo.',
      '.obeebbbbbbeebo.',
      '.oboeebbbbeeobo.',
      '.obbbbbbbbbbbso.',
      '.obommmmmmmobso.',
      '.obomtmmmmtobso.',
      '.obbommmmmmobso.',
      '.obbbooooooobso.',
      '.obwwbbbbbbbbso.',
      '..obbbbbbbbbbo..',
      '...oooooooooo...',
      '................',
    ],
    shadow: true,
  },

  bossTowerFirst: {
    palette: {
      o: '#1a1a2e', b: '#c8ccdc', s: '#787e9a', w: '#ffffff',
      c: '#4ac8e8', g: '#e8c24e', e: '#ff5a5a',
    },
    rows: [
      '................',
      '.....cccccc.....',
      '.o...oooooo...o.',
      '.obo.obbbbo.obo.',
      '.obo.obggbo.obo.',
      '.obbooeooeoobbo.',
      '.obbbobbbbbobbo.',
      '.obbbbbggbbbbbo.',
      '.obbbbbbbbbbbso.',
      '.obbbwwbbwwbbso.',
      '.obbbbbggbbbbso.',
      '..obbbbccbbbso..',
      '..obbo.cc.obbo..',
      '..oooo.cc.oooo..',
      '.......cc.......',
      '................',
    ],
    shadow: true,
  },

  bossTowerFinal: {
    palette: {
      o: '#141026', b: '#7ad8e0', s: '#2a7a96', w: '#ffffff',
      g: '#e8c24e', r: '#c86ae8', e: '#fff05a',
    },
    rows: [
      '................',
      '..oro.oooo.oro..',
      '.orroobbbboorro.',
      '.orrobbbbbborro.',
      '.orobbebbebboro.',
      '.oobbbebbebbboo.',
      '.oobbbboobbbboo.',
      '..obbggggggbbo..',
      '.oobbbggggbbbso.',
      '.oobbwwbbwwbbso.',
      '.obbbbbggbbbbso.',
      '..obbbbggbbbso..',
      '..obborrrrobbo..',
      '..oooorrrroooo..',
      '....rr....rr....',
      '................',
    ],
    shadow: true,
  },

  bossAbyss: {
    palette: {
      o: '#060210', b: '#3a1a5e', s: '#1c0832', v: '#a03ad8',
      e: '#ff2a4a', w: '#e0a8ff', g: '#ffd24a',
    },
    rows: [
      '................',
      '.o..o..oo..o..o.',
      '.oooooooooooooo.',
      '.obbbbbbbbbbbbo.',
      '.obeebbvvbbeebo.',
      '.obbbbvvvvbbbbo.',
      '.oeebvvoovvbeeo.',
      '.oeebvoggovbeeo.',
      '.obbbvoggovbbbo.',
      '.obeebvoovbeeso.',
      '.obeebbvvbbeeso.',
      '.obwbbbbbbbbbso.',
      '.oobbbbbbbbbbso.',
      '..oobbobbobboo..',
      '...ooo.oo.ooo...',
      '................',
    ],
    shadow: true,
  },
};
