/**
 * プレイヤー・ワナ・地形装飾・エフェクトのドット絵。
 *
 * 16x16 の文字グリッド。'.' は透明、それ以外は palette のキー。
 * 暗いダンジョンの床（#1d1524 〜 #3a2f26）の上に乗るので明度は高めに取る。
 * ワナは「床に埋まった装置」として 12x12 の平たい台座を共有し、
 * 中央の意匠と配色だけで描き分ける。
 */

import type { PixelSprite } from '../sprites.js';

export const WORLD_SPRITES: Record<string, PixelSprite> = {
  /** 風来人ナギ・北（背面）— 笠と背中だけを見せる */
  player0: {
    palette: { k: '#241a12', h: '#e3c37a', s: '#a8823c', c: '#4c6bb0', d: '#2d4278', b: '#e0d090' },
    rows: [
      '................',
      '......kkkk......',
      '.....khhhhk.....',
      '....khhhhhhk....',
      '...khhhhhhhhk...',
      '..khhhhhhhhhhk..',
      '.khhhhhhhhhhhhk.',
      '.kssssssssssssk.',
      '....kcccccck....',
      '...kcccddcccck..',
      '..kccccddcccck..',
      '.kcccccddccccck.',
      '.kcccccddccccbk.',
      '.kcccccddcccbbk.',
      '.kkddddddddddkk.',
      '................',
    ],
    shadow: true,
  },
  /** 風来人ナギ・北東 */
  player1: {
    palette: { k: '#241a12', h: '#e3c37a', s: '#a8823c', c: '#4c6bb0', d: '#2d4278', b: '#e0d090' },
    rows: [
      '................',
      '.......kkkk.....',
      '......khhhhk....',
      '.....khhhhhhk...',
      '....khhhhhhhhk..',
      '..khhhhhhhhhhk..',
      '.khhhhhhhhhhhhk.',
      '.kssssssssssssk.',
      '.....kcccccck...',
      '....kccccddcck..',
      '..kcccccddcccck.',
      '.kcccccddccccck.',
      '.kcccccddcccbbk.',
      '.kcccccddcccbck.',
      '.kkddddddddddkk.',
      '................',
    ],
    shadow: true,
  },
  /** 風来人ナギ・東（横顔・刀は背後へ） */
  player2: {
    palette: { k: '#241a12', h: '#e3c37a', s: '#a8823c', f: '#f2cb9c', c: '#4c6bb0', d: '#2d4278', b: '#e0d090' },
    rows: [
      '................',
      '......kkk.......',
      '.....khhhk......',
      '....khhhhhk.....',
      '...khhhhhhhk....',
      '..khhhhhhhhhk...',
      '.khhhhhhhhhhhk..',
      '.ksssssssssssk..',
      '......kfffffk...',
      '......kfffkfk...',
      '......kffffk....',
      '..kccccccccck...',
      '.kddcccccccck...',
      '.kddbbbccccck...',
      '..kddddddddk....',
      '................',
    ],
    shadow: true,
  },
  /** 風来人ナギ・南東 */
  player3: {
    palette: { k: '#241a12', h: '#e3c37a', s: '#a8823c', f: '#f2cb9c', c: '#4c6bb0', d: '#2d4278', b: '#e0d090' },
    rows: [
      '................',
      '.......kkkk.....',
      '......khhhhk....',
      '.....khhhhhhk...',
      '....khhhhhhhhk..',
      '..khhhhhhhhhhk..',
      '.khhhhhhhhhhhhk.',
      '.kssssssssssssk.',
      '.....kffffffk...',
      '.....kfkffkfk...',
      '......kffffk....',
      '..kcccccccccck..',
      '.kcccccccccccbk.',
      '.kcbbbbbbbbbbck.',
      '.kkddddddddddkk.',
      '................',
    ],
    shadow: true,
  },
  /** 風来人ナギ・南（正面）— 三度笠・マント・腰の刀 */
  player4: {
    palette: { k: '#241a12', h: '#e3c37a', s: '#a8823c', f: '#f2cb9c', c: '#4c6bb0', d: '#2d4278', b: '#e0d090' },
    rows: [
      '................',
      '......kkkk......',
      '.....khhhhk.....',
      '....khhhhhhk....',
      '...khhhhhhhhk...',
      '..khhhhhhhhhhk..',
      '.khhhhhhhhhhhhk.',
      '.kssssssssssssk.',
      '....kffffffk....',
      '....kfkffkfk....',
      '.....kffffk.....',
      '..kcccccccccck..',
      '.kcccccccccccbk.',
      '.kcbbbbbbbbbbck.',
      '.kkddddddddddkk.',
      '................',
    ],
    shadow: true,
  },
  /** 風来人ナギ・南西 */
  player5: {
    palette: { k: '#241a12', h: '#e3c37a', s: '#a8823c', f: '#f2cb9c', c: '#4c6bb0', d: '#2d4278', b: '#e0d090' },
    rows: [
      '................',
      '.....kkkk.......',
      '....khhhhk......',
      '...khhhhhhk.....',
      '..khhhhhhhhk....',
      '..khhhhhhhhhhk..',
      '.khhhhhhhhhhhhk.',
      '.kssssssssssssk.',
      '...kffffffk.....',
      '...kfkffkfk.....',
      '....kffffk......',
      '..kcccccccccck..',
      '.kbccccccccccck.',
      '.kcbbbbbbbbbbck.',
      '.kkddddddddddkk.',
      '................',
    ],
    shadow: true,
  },
  /** 風来人ナギ・西（横顔） */
  player6: {
    palette: { k: '#241a12', h: '#e3c37a', s: '#a8823c', f: '#f2cb9c', c: '#4c6bb0', d: '#2d4278', b: '#e0d090' },
    rows: [
      '................',
      '.......kkk......',
      '......khhhk.....',
      '.....khhhhhk....',
      '....khhhhhhhk...',
      '...khhhhhhhhhk..',
      '..khhhhhhhhhhhk.',
      '..ksssssssssssk.',
      '...kfffffk......',
      '...kfkfffk......',
      '....kffffk......',
      '...kccccccccck..',
      '...kccccccccddk.',
      '...kcccccbbbddk.',
      '....kddddddddk..',
      '................',
    ],
    shadow: true,
  },
  /** 風来人ナギ・北西 */
  player7: {
    palette: { k: '#241a12', h: '#e3c37a', s: '#a8823c', c: '#4c6bb0', d: '#2d4278', b: '#e0d090' },
    rows: [
      '................',
      '.....kkkk.......',
      '....khhhhk......',
      '...khhhhhhk.....',
      '..khhhhhhhhk....',
      '..khhhhhhhhhhk..',
      '.khhhhhhhhhhhhk.',
      '.kssssssssssssk.',
      '...kcccccck.....',
      '..kccddcccck....',
      '.kccccddccccck..',
      '.kcccccddccccck.',
      '.kbbcccddccccck.',
      '.kcbcccddccccck.',
      '.kkddddddddddkk.',
      '................',
    ],
    shadow: true,
  },
  /** 矢のワナ — 鋼の鏃が床から覗く */
  trapArrow: {
    palette: { k: '#17120d', p: '#6e6458', q: '#413a31', a: '#d8dee6', s: '#9a7440' },
    rows: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kppppppppppk..',
      '..kppppaappppk..',
      '..kpppaaaapppk..',
      '..kppaaaaaappk..',
      '..kppppssppppk..',
      '..kppppssppppk..',
      '..kppppssppppk..',
      '..kpppqssqpppk..',
      '..kppqqssqqppk..',
      '..kppppppppppk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 毒矢のワナ — 矢と同じ形、鏃と台座を毒色に */
  trapPoison: {
    palette: { k: '#141024', p: '#5e4d72', q: '#38294a', a: '#9ce85c', s: '#7a5aa0' },
    rows: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kppppppppppk..',
      '..kppppaappppk..',
      '..kpppaaaapppk..',
      '..kppaaaaaappk..',
      '..kppppssppppk..',
      '..kppppssppppk..',
      '..kppppssppppk..',
      '..kpppqssqpppk..',
      '..kppqqssqqppk..',
      '..kppppppppppk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 落とし穴 — 縁石に囲まれた黒い口 */
  trapPit: {
    palette: { k: '#17120e', p: '#6a5f52', q: '#3c352c', d: '#241e18' },
    rows: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kppppppppppk..',
      '..kpqqqqqqqqpk..',
      '..kpqddddddqpk..',
      '..kqddddddddqk..',
      '..kqddddddddqk..',
      '..kqddddddddqk..',
      '..kqddddddddqk..',
      '..kpqddddddqpk..',
      '..kpqqqqqqqqpk..',
      '..kppppppppppk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** ガスのワナ — 通気孔から噴き出す霧 */
  trapGas: {
    palette: { k: '#132018', p: '#5f6d58', q: '#36402f', g: '#8fe07a', w: '#ccf7b8' },
    rows: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kppppppppppk..',
      '..kpppggggpppk..',
      '..kpggwggwggpk..',
      '..kggggggggggk..',
      '..kpggggggggpk..',
      '..kppqqppqqppk..',
      '..kppqqppqqppk..',
      '..kppppppppppk..',
      '..kpqqqqqqqqpk..',
      '..kppppppppppk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** トラばさみ — 噛み合う牙 */
  trapBear: {
    palette: { k: '#14100c', p: '#5f564b', q: '#2c2823', m: '#9aa3ad', t: '#e2e9f0' },
    rows: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kppppppppppk..',
      '..kpmmmmmmmmpk..',
      '..kptqtqtqtqpk..',
      '..kqqqqqqqqqqk..',
      '..kqqqqqqqqqqk..',
      '..kpqtqtqtqtpk..',
      '..kpmmmmmmmmpk..',
      '..kppmqqqqmppk..',
      '..kpppmqqmpppk..',
      '..kppppppppppk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 錆びのワナ — 刃を溶かす錆の泉 */
  trapRust: {
    palette: { k: '#1a1208', p: '#6b5a42', m: '#c2c8d0', r: '#bf6a2a', o: '#eb9c3e' },
    rows: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kppppppppppk..',
      '..kppppmmppppk..',
      '..kpppmmmmpppk..',
      '..kpprmmmmrppk..',
      '..kprrommmorpk..',
      '..krroommoorrk..',
      '..krrooorroork..',
      '..kprroooorrpk..',
      '..kpprrrrrrppk..',
      '..kppppppppppk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** デロデロのワナ — 泡立つ腐汁 */
  trapRot: {
    palette: { k: '#131a10', p: '#5d6742', g: '#7fa33c', d: '#3d5220', w: '#c6e26c' },
    rows: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kppppppppppk..',
      '..kppddggddppk..',
      '..kpdgwggwgdpk..',
      '..kdggggggggdk..',
      '..kdgwggggwgdk..',
      '..kdggggggggdk..',
      '..kpdgggwggdpk..',
      '..kpddggggddpk..',
      '..kppddddddppk..',
      '..kppppppppppk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 警報のワナ — 床に据えられた鐘 */
  trapAlarm: {
    palette: { k: '#1a1408', p: '#635a48', y: '#eac53f', o: '#a8801c', w: '#fff3b0' },
    rows: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kppppppppppk..',
      '..kppppyyppppk..',
      '..kpppyyyypppk..',
      '..kppyywwyyppk..',
      '..kpyyywwyyypk..',
      '..kpyyyyyyyypk..',
      '..kyyyyyyyyyyk..',
      '..kpoooooooopk..',
      '..kppppooppppk..',
      '..kppppppppppk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 召喚のワナ — 魔法陣から覗く眼と牙 */
  trapSummon: {
    palette: { k: '#180f22', p: '#4a3758', q: '#2b1d3c', m: '#b96ce8', w: '#eecaff' },
    rows: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kppppppppppk..',
      '..kppppppppppk..',
      '..kppmmmmmmppk..',
      '..kpmqqqqqqmpk..',
      '..kmqqwqqwqqmk..',
      '..kmqqqqqqqqmk..',
      '..kmqwwwwwwqmk..',
      '..kpmqqqqqqmpk..',
      '..kppmmmmmmppk..',
      '..kppppppppppk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** ワープのワナ — 同心円の渦 */
  trapWarp: {
    palette: { k: '#101a2a', p: '#44506b', c: '#5ad0e8', d: '#243350', w: '#ccf6ff' },
    rows: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kppppppppppk..',
      '..kpppccccpppk..',
      '..kpccddddccpk..',
      '..kpcdcwwcdcpk..',
      '..kcddcwwcddck..',
      '..kcddcwwcddck..',
      '..kpcdcwwcdcpk..',
      '..kpccddddccpk..',
      '..kpppccccpppk..',
      '..kppppppppppk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 回転板 — 回る円盤 */
  trapSpin: {
    palette: { k: '#1a140e', p: '#6d5d46', q: '#3d3325', y: '#e3bb4f', w: '#f8e8b4' },
    rows: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kppppppppppk..',
      '..kpppyyyypppk..',
      '..kpyyqqqqyypk..',
      '..kyyqqwwqqyyk..',
      '..kyqqwwwwqqyk..',
      '..kyqqwwwwqqyk..',
      '..kyyqqwwqqyyk..',
      '..kpyyqqqqyypk..',
      '..kpppyyyypppk..',
      '..kppppppppppk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 地雷 — 赤い信管の覗く鉄の椀 */
  trapMine: {
    palette: { k: '#140d0d', p: '#5e4e45', d: '#2d2d34', m: '#727a85', r: '#ff4b3a' },
    rows: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kppppppppppk..',
      '..kppppmmppppk..',
      '..kpppmrrmpppk..',
      '..kppmddddmppk..',
      '..kpmddddddmpk..',
      '..kmdddrrdddmk..',
      '..kmdddrrdddmk..',
      '..kpmddddddmpk..',
      '..kppmmmmmmppk..',
      '..kppppppppppk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 鈍足のワナ — 重石 */
  trapSlow: {
    palette: { k: '#101825', p: '#4d5e70', b: '#7fa8c8', d: '#2b3c4e', w: '#d2e8f6' },
    rows: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kppppppppppk..',
      '..kpppbbbbpppk..',
      '..kppbwwwwbppk..',
      '..kpbddddddbpk..',
      '..kbddwdddddbk..',
      '..kbddddddddbk..',
      '..kbddddddddbk..',
      '..kpbddddddbpk..',
      '..kppbbbbbbppk..',
      '..kppppppppppk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 石像のワナ — 赤く光る石の顔 */
  trapStatue: {
    palette: { k: '#181510', p: '#5f5a50', s: '#928b7d', q: '#3b372f', r: '#ff6b5a' },
    rows: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kppppppppppk..',
      '..kppssssssppk..',
      '..kpsssssssspk..',
      '..kssrrssrrssk..',
      '..kssqqssqqssk..',
      '..ksssqqqqsssk..',
      '..kssqqqqqqssk..',
      '..kpsssssssspk..',
      '..kppssssssppk..',
      '..kppppppppppk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 呪いのワナ — 紫の靄をまとう髑髏 */
  trapCurse: {
    palette: { k: '#140a1c', p: '#432e56', v: '#8f52d6', w: '#e2c6ff', d: '#251638' },
    rows: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kppppppppppk..',
      '..kpppwwwwpppk..',
      '..kppwwwwwwppk..',
      '..kpwwdwwdwwpk..',
      '..kpwwdwwdwwpk..',
      '..kpwwwwwwwwpk..',
      '..kppwdwwdwppk..',
      '..kpppwwwwpppk..',
      '..kppvvvvvvppk..',
      '..kppppppppppk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 空腹のワナ — しゃぶられた骨 */
  trapHunger: {
    palette: { k: '#1a1208', p: '#5d5038', b: '#ecdfc2', o: '#ab9260', q: '#3a2e1c' },
    rows: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kppppppppppk..',
      '..kppppppppppk..',
      '..kppqqqqqqppk..',
      '..kpbbppppbbpk..',
      '..kbbbbbbbbbbk..',
      '..kboooooooobk..',
      '..kpbbppppbbpk..',
      '..kppqqqqqqppk..',
      '..kppppppppppk..',
      '..kppppppppppk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 封印のワナ — 朱の呪印を書いた御札 */
  trapSeal: {
    palette: { k: '#1a1414', p: '#554e46', w: '#f0e7d4', r: '#c93f3f', q: '#8c2424' },
    rows: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kppppppppppk..',
      '..kpppwwwwpppk..',
      '..kpppwrrwpppk..',
      '..kpppwwwwpppk..',
      '..kpppwrrwpppk..',
      '..kpppwwwwpppk..',
      '..kpppwrrwpppk..',
      '..kpppwwwwpppk..',
      '..kpppqqqqpppk..',
      '..kppppppppppk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** モンスターハウスのワナ — 眼だらけの門 */
  trapHouse: {
    palette: { k: '#1a1010', p: '#523d36', r: '#d44133', y: '#ffd15c', d: '#2b1b19' },
    rows: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kppppppppppk..',
      '..kppppppppppk..',
      '..kpprrrrrrppk..',
      '..kprddddddrpk..',
      '..krddyddyddrk..',
      '..krddddddddrk..',
      '..krdyddddydrk..',
      '..kprddddddrpk..',
      '..kpprrrrrrppk..',
      '..kppppppppppk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 転落のワナ — 持ち物が吸い込まれる裂け目 */
  trapDrop: {
    palette: { k: '#161210', p: '#5e5449', q: '#332b24', y: '#e5c465', w: '#fff0bb' },
    rows: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kppppppppppk..',
      '..kppppyyppppk..',
      '..kpppywwypppk..',
      '..kpppyyyypppk..',
      '..kppppyyppppk..',
      '..kppppppppppk..',
      '..kpqqqqqqqqpk..',
      '..kqqqqqqqqqqk..',
      '..kpqqqqqqqqpk..',
      '..kppppppppppk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 噴火のワナ — 噴き上がる火 */
  trapLava: {
    palette: { k: '#1c0a06', p: '#5f3422', r: '#e8501e', o: '#ffa63c', w: '#ffe28a' },
    rows: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kppppppppppk..',
      '..kppppooppppk..',
      '..kpppowwopppk..',
      '..kppoowwooppk..',
      '..kpoorwwroopk..',
      '..kprrrwwrrrpk..',
      '..kprrrrrrrrpk..',
      '..kpprrrrrrppk..',
      '..kppprrrrpppk..',
      '..kppppppppppk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 水没のワナ — 噴き出す水 */
  trapWater: {
    palette: { k: '#0c1a26', p: '#375b70', b: '#3fa8d8', c: '#8fe0f5', w: '#dff6ff' },
    rows: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kppppppppppk..',
      '..kppppccppppk..',
      '..kpppcwwcpppk..',
      '..kppcwwwwcppk..',
      '..kpbccccccbpk..',
      '..kbbbbbbbbbbk..',
      '..kbbcbbbbcbbk..',
      '..kpbbbbbbbbpk..',
      '..kppbbbbbbppk..',
      '..kppppppppppk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 降り階段 — 沈み込む四角の段 */
  stairsDown: {
    palette: { k: '#0f0f16', w: '#c9d0e0', s: '#7c8398', q: '#2b303e' },
    rows: [
      '................',
      '................',
      '..kkkkkkkkkkkk..',
      '..kwwwwwwwwwwk..',
      '..kwkkkkkkkkwk..',
      '..kwksssssskwk..',
      '..kwkskkkkskwk..',
      '..kwkskqqkskwk..',
      '..kwkskqqkskwk..',
      '..kwkskkkkskwk..',
      '..kwksssssskwk..',
      '..kwkkkkkkkkwk..',
      '..kwwwwwwwwwwk..',
      '..kkkkkkkkkkkk..',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 壁の上面 — 積み石の目地 */
  wallTop: {
    palette: { d: '#251d17', m: '#4c3e32', w: '#7f6c5a' },
    rows: [
      '................',
      '................',
      '.wwwwwwwwwwwwww.',
      '.dddddddddddddd.',
      '.....m.....m....',
      '.....m.....m....',
      '.wwwwwwwwwwwwww.',
      '.dddddddddddddd.',
      '..m.....m.....m.',
      '..m.....m.....m.',
      '.wwwwwwwwwwwwww.',
      '.dddddddddddddd.',
      '.....m.....m....',
      '.....m.....m....',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 床の装飾 1 — 走るひび割れ */
  floorDecor1: {
    palette: { d: '#191410', m: '#2e2720', w: '#4b4034' },
    rows: [
      '................',
      '................',
      '................',
      '...dd...........',
      '...mdd..........',
      '....mdd....w....',
      '.....mdd........',
      '......mddd......',
      '........mdd.....',
      '.........mddd...',
      '..........mdd...',
      '..w........mdd..',
      '............dd..',
      '................',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 床の装飾 2 — 転がる小石 */
  floorDecor2: {
    palette: { k: '#1b1610', s: '#5a4e40', w: '#80715e' },
    rows: [
      '................',
      '................',
      '................',
      '....kk..........',
      '...kwsk.........',
      '...kssk.........',
      '....kk....kkk...',
      '.........kwssk..',
      '.........ksssk..',
      '..........kkk...',
      '.....kkk........',
      '....kwssk.......',
      '....ksssk.......',
      '.....kkk........',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 水面のきらめき */
  waterDecor: {
    palette: { d: '#123a52', b: '#4fb7e0', w: '#d8f5ff' },
    rows: [
      '................',
      '................',
      '................',
      '...dbbbd........',
      '....www.........',
      '................',
      '.........dbbbd..',
      '..........www...',
      '................',
      '..dbbbbd........',
      '...wwww.........',
      '................',
      '........dbbd....',
      '.........ww.....',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 溶岩の泡 */
  lavaDecor: {
    palette: { d: '#5e1607', r: '#ff7a2a', w: '#ffe07a' },
    rows: [
      '................',
      '................',
      '................',
      '....dd..........',
      '...dwwd.........',
      '...drrd.........',
      '....dd......dd..',
      '..........dwwd..',
      '..........drrd..',
      '...........dd...',
      '................',
      '......dd........',
      '.....dwrd.......',
      '......dd........',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 打撃の星 — 四方に伸びる衝撃 */
  fxHit: {
    palette: { k: '#3f2109', y: '#ffd24a', w: '#fff8d2', o: '#ff9a2a' },
    rows: [
      '................',
      '................',
      '.......kk.......',
      '......kyyk......',
      '......kyyk......',
      '......kyyk......',
      '..kkkkyyyykkkk..',
      '.kyyyywwwwyyyyk.',
      '.kyyoywwwwyoyyk.',
      '..kkkkyyyykkkk..',
      '......kyyk......',
      '......kyyk......',
      '......kyyk......',
      '.......kk.......',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 斬撃 — 右上から左下へ抜ける太刀筋 */
  fxSlash: {
    palette: { k: '#20283c', w: '#ffffff', b: '#8fc4ff' },
    rows: [
      '................',
      '................',
      '...........kk...',
      '..........kwwk..',
      '.........kwwbk..',
      '........kwwbbk..',
      '.......kwwbbk...',
      '......kwwbbk....',
      '.....kwwbbk.....',
      '....kwwbbk......',
      '...kwwbbk.......',
      '..kwwbk.........',
      '..kwbk..........',
      '..kk............',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 魔法の輝き — 菱形の光 */
  fxMagic: {
    palette: { k: '#241a3a', v: '#b07bff', w: '#f4e6ff', c: '#7de0ff' },
    rows: [
      '................',
      '................',
      '.......kk.......',
      '......kwwk......',
      '.....kwvvwk.....',
      '....kwvvvvwk....',
      '...kwvvvvvvwk...',
      '.kkwvvvccvvvwkk.',
      '.kkwvvvccvvvwkk.',
      '...kwvvvvvvwk...',
      '....kwvvvvwk....',
      '.....kwvvwk.....',
      '......kwwk......',
      '.......kk.......',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 炎 — 立ち上る火柱 */
  fxFire: {
    palette: { k: '#3a1204', r: '#e63c14', o: '#ff9424', y: '#ffe266' },
    rows: [
      '................',
      '................',
      '.......kk.......',
      '......krrk......',
      '.....kroork.....',
      '....kroooork....',
      '...kroooooork...',
      '..krooyyyyoork..',
      '..krooyyyyoork..',
      '..kroyyyyyyork..',
      '..kroyyyyyyork..',
      '...kroyyyyork...',
      '....kroooork....',
      '.....kkkkkk.....',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 電撃 — 折れ曲がる稲妻 */
  fxSpark: {
    palette: { k: '#1c2a4a', w: '#ffffff', b: '#5fd0ff' },
    rows: [
      '................',
      '................',
      '........kkk.....',
      '.......kwwk.....',
      '......kwwbk.....',
      '.....kwwbk......',
      '....kwwbbbbk....',
      '.....kkkwwwbk...',
      '........kwwbk...',
      '.......kwwbk....',
      '......kwwbk.....',
      '.....kwwbk......',
      '....kwbk........',
      '....kkk.........',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 煙 — もくもくと流れる雲 */
  fxSmoke: {
    palette: { k: '#2a2630', g: '#7d7a88', w: '#bab7c6', d: '#4b4854' },
    rows: [
      '................',
      '................',
      '................',
      '......kkk.......',
      '.....kwwwk......',
      '...kkkwwgk......',
      '..kwwwwwggk.....',
      '..kwwwgggggkkk..',
      '..kwgggggggggk..',
      '..kgggggdddggk..',
      '...kgggdddddgk..',
      '...kkgddddddkk..',
      '.....kkddddkk...',
      '.......kkkk.....',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 回復の光 — 十字の輝きと舞う光の粒 */
  fxHeal: {
    palette: { k: '#14401f', g: '#5ce07a', w: '#eaffdc' },
    rows: [
      '................',
      '..kgk......kgk..',
      '......kkkk......',
      '......kwwk......',
      '......kggk......',
      '..kkkkkwwkkkkk..',
      '..kwggwwwwggwk..',
      '..kwggwwwwggwk..',
      '..kkkkkwwkkkkk..',
      '......kggk......',
      '......kwwk......',
      '......kkkk......',
      '...kgk....kgk...',
      '................',
      '................',
      '................',
    ],
    shadow: false,
  },
  /** 渦 — 吸い込まれる同心の輪 */
  fxWarp: {
    palette: { k: '#1a1030', v: '#8a5fe0', c: '#57e6ff', w: '#e8f6ff' },
    rows: [
      '................',
      '................',
      '.....kkkkkk.....',
      '...kkvvvvvvkk...',
      '..kvvvvvvvvvvk..',
      '.kvvvkkkkkkvvvk.',
      '.kvvkcccccckvvk.',
      '.kvkcckwwkcckvk.',
      '.kvkcckwwkcckvk.',
      '.kvvkcccccckvvk.',
      '.kvvvkkkkkkvvvk.',
      '..kvvvvvvvvvvk..',
      '...kkvvvvvvkk...',
      '.....kkkkkk.....',
      '................',
      '................',
    ],
    shadow: false,
  },
};
